add safety checks with error messages; remove positional variables with defaults

diff --git a/bib/bib2blog b/bib/bib2blog
--- a/bib/bib2blog
+++ b/bib/bib2blog
@@ -2,11 +2,9 @@
 
 # Basic usage
 usage() {
-    echo "
-    Convert bibtex entry to pelican blog entry
+    echo "Convert bibtex entry to pelican blog entry
     
-    Usage: bib2blog [options] -i BIBFILE -k BIBKEY
-    "
+Usage: bib2blog [options] -i BIBFILE -k BIBKEY"
 }
 
 # Detailed help
@@ -101,6 +99,13 @@ while [ "$1" != "" ]; do
     esac
     shift
 done
+
+# input files must exist
+if [ -z "$bibfile" -o -z "$bibkey" ]; then
+    echo "Error: missing argument!\n"
+    usage
+    exit 1
+fi
 
 
 ######################
diff --git a/bib/create_bibkey b/bib/create_bibkey
--- a/bib/create_bibkey
+++ b/bib/create_bibkey
@@ -2,11 +2,9 @@
 
 # Basic usage
 usage() {
-    echo "
-    Produce blog entry for every item in bibtex file
+    echo "Produce blog entry for every item in bibtex file
 
-    Usage: create_bibkey [options] -i BIBFILE
-    "
+Usage: create_bibkey [options] -i BIBFILE"
 }
 
 # Detailed help
@@ -38,9 +36,7 @@ Options:
 
 website_path="${HOME}/dev/website"
 bib_path="${website_path}/bib"
-bibfile="${bib_path}/references.bib"
 tmppath="/tmp"
-outfile="${tmppath}/$(basename $bibfile).keys"
 
 # options
 while [ "$1" != "" ]; do
@@ -72,6 +68,18 @@ while [ "$1" != "" ]; do
     esac
     shift
 done
+
+# input file must exist
+if [ -z $bibfile ]; then
+    echo "Error: missing argument!\n"
+    usage
+    exit 1
+fi
+
+# also set a default output file if none specified
+if [ -z $outfile ]; then
+    outfile="${tmppath}/$(basename $bibfile).keys"
+fi
 
 
 ##########
diff --git a/bib/create_bibliography b/bib/create_bibliography
--- a/bib/create_bibliography
+++ b/bib/create_bibliography
@@ -2,11 +2,9 @@
 
 # Basic usage
 usage() {
-    echo "
-    Produce formatted list of publications and presentations 
+    echo "Produce formatted list of publications and presentations 
 
-    Usage: create_bibliography [options] -p PUBLICATION-FILE -t PRESENTATION-FILE
-    "
+Usage: create_bibliography [options] -p PUBLICATION-FILE -t PRESENTATION-FILE -a AUTHORNAME"
 }
 
 # Detailed help
@@ -42,10 +40,6 @@ Options:
 ###############
 
 title="Output"
-author="Thomas Graf"
-publications=${1-"${HOME}/Latex/graf.bib"}
-presentations=${2-"${HOME}/Latex/graf_presentations.bib"}
-
 website_path="${HOME}/dev/website"
 bib_path="${website_path}/bib"
 tmppath="/tmp"
@@ -97,6 +91,12 @@ while [ "$1" != "" ]; do
     esac
     shift
 done
+
+if [ -z "$publications" -o -z "$presentations" -o -z "$author" ]; then
+    echo "Error: missing argument!\n"
+    usage
+    exit 1
+fi
 
 
 ############
